"""v3

Revision ID: ed522fcff78b
Revises: 10453541dcb6
Create Date: 2026-04-03 02:39:58.915067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed522fcff78b'
down_revision = '10453541dcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_base64', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_base64', sa.Text(), nullable=True))

    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_facture', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('prix_unitaire', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('client_nom', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('client_telephone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('client_adresse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('facture_envoyee', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['numero_facture'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('facture_envoyee')
        batch_op.drop_column('client_adresse')
        batch_op.drop_column('client_telephone')
        batch_op.drop_column('client_nom')
        batch_op.drop_column('prix_unitaire')
        batch_op.drop_column('numero_facture')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo_base64')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_base64')

    # ### end Alembic commands ###
